openhab_api_url: "http://localhost:8080/rest"
nuimo_mac_address: "96:EC:C6:4D:05:BA"
bluetooth_adapter: hci0
rotation_icon: circle

# The key mapping in this example file contains 2 modes:
# - the default mode which is used to control the currently the selected app / item
# - the menue mode which allows to select other apps / items
# The menue mode is active while the button is pressed.
# So you can navigate between your apps / items as long as you hold the button.
key_mapping:
    # Default mode is mandatory and the initial key mapping after nuimo startup
    default:
      # The mode can be changed with the MENUE.CHANGEMODE=newmode command. "newmode" must be a mode that is listed in this key mapping
      BUTTON_PRESS: "MENUE.CHANGEMODE=menue"
      BUTTON_HOLD: "MENUE.SHOWAPP"
      BUTTON_CLICK: "OPENHAB.TOGGLE"
      SWIPE_UP: "MENUE.PARENT"
      SWIPE_DOWN: "MENUE.CHILD"
      SWIPE_LEFT: "OPENHAB.PREVIOUS"
      SWIPE_RIGHT: "OPENHAB.NEXT"
      ROTATION: "OPENHAB.WHEELDIMMER"
    # More modes can be dynamically added
    menue:
      SWIPE_UP: "MENUE.PARENT"
      SWIPE_DOWN: "MENUE.CHILD"
      SWIPE_LEFT: "MENUE.PREVIOUS"
      SWIPE_RIGHT: "MENUE.NEXT"
      BUTTON_RELEASE: "MENUE.CHANGEMODE=default"
      ROTATION: "MENUE.WHEELNAVIGATION"

default_gesture_command_mapping:
    TOUCH_BOTTOM: "OFF"
    #BUTTON_PRESS: "ON"     # Normally, you want to map either BUTTON_PRESS or BUTTON_RELEASE, but not both. Otherwise, 2 commands would be send (first one after pressing, second after releasing the button).
    BUTTON_RELEASE: "ON"
    TOUCH_RIGHT: "NEXT"
    TOUCH_LEFT: "PREVIOUS"